//! Transform engine for processing device data.
//!
//! This module provides the execution engine for data transformations,
//! converting raw device JSON into standardized metrics.
//!
//! # AI-Native Design
//!
//! Transforms use JavaScript code generated by AI:
//! - User describes intent in natural language
//! - AI generates JavaScript transformation code
//! - Code executes in a sandboxed Boa JS context
//! - Results become virtual metrics
//!
//! # Auto-Registration

#![allow(clippy::too_many_arguments)]
//! Transform outputs are automatically registered as data sources when
//! the transform executes successfully, making them available for:
//! - Dashboard components
//! - Rule conditions
//! - AI Agent queries
//!
//! # JavaScript Extension API
//!
//! Transforms can call extensions via `extensions.invoke(extension_id, command, params)`:
//! ```javascript
//! const result = extensions.invoke('weather.ext', 'get_current', { location: 'Beijing' })
//! return result.temp_f
//! ```

use super::output_registry::TransformOutputRegistry;
use super::store::SharedAutomationStore;
use std::sync::Arc;

// Import ExtensionRegistry for extension invoke support
use neomind_core::event::MetricValue;

pub struct TransformResult {
    /// Output metrics produced
    pub metrics: Vec<TransformedMetric>,
    /// Any warnings generated during transformation
    pub warnings: Vec<String>,
}

/// A transformed metric ready for storage/publication
#[derive(Debug, Clone, serde::Serialize)]
pub struct TransformedMetric {
    /// Device ID (original device that triggered the transform)
    pub device_id: String,
    /// Transform ID that produced this metric (set after creation)
    #[serde(default)]
    pub transform_id: Option<String>,
    /// Metric name
    pub metric: String,
    /// Metric value (supports floats, integers, booleans, strings, and complex JSON)
    pub value: MetricValue,
    /// Timestamp (Unix timestamp)
    pub timestamp: i64,
    /// Quality indicator (0-1)
    pub quality: Option<f32>,
}

impl TransformedMetric {
    /// Create storage device ID for telemetry
    /// Format: "transform:{transform_id}" for proper querying from Data Explorer
    pub fn storage_device_id(&self) -> String {
        format!(
            "transform:{}",
            self.transform_id.as_deref().unwrap_or("unknown")
        )
    }
}

/// Transform engine - executes data transformations
pub struct TransformEngine {
    /// Persistent telemetry storage for window-based aggregations.
    /// [2026-08 fix] TimeSeriesAggregation used to read an in-RAM cache that
    /// NOTHING ever populated (the feeding API had zero callers) — every
    /// aggregation failed with "No data points found" while recording
    /// Completed. It now queries the real telemetry store: full history,
    /// restart-safe, unit-aligned (seconds — device metrics storage writes
    /// `Utc::now().timestamp()`).
    time_series_storage: Option<Arc<neomind_devices::TimeSeriesStorage>>,
    /// JavaScript executor for AI-generated code
    js_executor: JsTransformExecutor,
    /// Phase 4.1: Extension registry for preprocessing
    extension_registry: Option<Arc<neomind_core::extension::registry::ExtensionRegistry>>,
    /// Output registry for auto-registering Transform outputs as data sources
    output_registry: Arc<TransformOutputRegistry>,
    /// Automation store for recording execution history
    automation_store: Option<Arc<SharedAutomationStore>>,
    /// HTTP client for Extension input resolution (e.g., url_to_base64)
    http_client: reqwest::Client,
}

impl Default for TransformEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl TransformEngine {
    /// Create a new transform engine
    pub fn new() -> Self {
        Self {
            time_series_storage: None,
            js_executor: JsTransformExecutor::new(),
            extension_registry: None,
            output_registry: Arc::new(TransformOutputRegistry::new()),
            automation_store: None,
            // [bounded fetch] reqwest's default client has NO total timeout;
            // url_to_base64 fetches device-controlled URLs — a hanging or
            // huge response stalled the transform task (and could OOM the
            // process). 30s total, 10MB body cap enforced at the read site.
            http_client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(30))
                .connect_timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_default(),
        }
    }
}
impl TransformEngine {
    /// Attach the persistent telemetry store (enables window-based
    /// TimeSeriesAggregation over real history).
    pub fn with_time_series_storage(
        mut self,
        storage: Arc<neomind_devices::TimeSeriesStorage>,
    ) -> Self {
        self.time_series_storage = Some(storage);
        self
    }
}
impl TransformEngine {
    /// Phase 4.1: Create a transform engine with extension registry
    pub fn with_extension_registry(
        extension_registry: Arc<neomind_core::extension::registry::ExtensionRegistry>,
    ) -> Self {
        Self {
            time_series_storage: None,
            js_executor: JsTransformExecutor::new(),
            extension_registry: Some(extension_registry),
            output_registry: Arc::new(TransformOutputRegistry::new()),
            automation_store: None,
            // [bounded fetch] reqwest's default client has NO total timeout;
            // url_to_base64 fetches device-controlled URLs — a hanging or
            // huge response stalled the transform task (and could OOM the
            // process). 30s total, 10MB body cap enforced at the read site.
            http_client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(30))
                .connect_timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_default(),
        }
    }
}
impl TransformEngine {
    /// Create a transform engine with a shared output registry
    ///
    /// This allows multiple components to access the same registry
    /// and query Transform outputs as data sources.
    pub fn with_output_registry(output_registry: Arc<TransformOutputRegistry>) -> Self {
        Self {
            time_series_storage: None,
            js_executor: JsTransformExecutor::new(),
            extension_registry: None,
            output_registry,
            automation_store: None,
            // [bounded fetch] reqwest's default client has NO total timeout;
            // url_to_base64 fetches device-controlled URLs — a hanging or
            // huge response stalled the transform task (and could OOM the
            // process). 30s total, 10MB body cap enforced at the read site.
            http_client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(30))
                .connect_timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_default(),
        }
    }
}
impl TransformEngine {
    /// Create a transform engine with both extension and output registries
    pub fn with_registries(
        extension_registry: Option<Arc<neomind_core::extension::registry::ExtensionRegistry>>,
        output_registry: Arc<TransformOutputRegistry>,
    ) -> Self {
        Self {
            time_series_storage: None,
            js_executor: JsTransformExecutor::new(),
            extension_registry,
            output_registry,
            automation_store: None,
            // [bounded fetch] reqwest's default client has NO total timeout;
            // url_to_base64 fetches device-controlled URLs — a hanging or
            // huge response stalled the transform task (and could OOM the
            // process). 30s total, 10MB body cap enforced at the read site.
            http_client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(30))
                .connect_timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_default(),
        }
    }
}
impl TransformEngine {
    /// Set the automation store for recording execution history
    pub fn with_automation_store(mut self, store: Arc<SharedAutomationStore>) -> Self {
        self.automation_store = Some(store);
        self
    }
}
impl TransformEngine {
    /// Phase 4.1: Set the extension registry
    pub fn set_extension_registry(
        &mut self,
        registry: Arc<neomind_core::extension::registry::ExtensionRegistry>,
    ) {
        self.extension_registry = Some(registry);
    }
}
impl TransformEngine {
    /// Set the output registry
    pub fn set_output_registry(&mut self, registry: Arc<TransformOutputRegistry>) {
        self.output_registry = registry;
    }
}
impl TransformEngine {
    /// Get the output registry
    ///
    /// This allows querying Transform outputs as data sources.
    pub fn output_registry(&self) -> Arc<TransformOutputRegistry> {
        Arc::clone(&self.output_registry)
    }
}
impl TransformEngine {
    /// Get the JS executor (for testing purposes)
    pub fn js_executor(&self) -> &JsTransformExecutor {
        &self.js_executor
    }

    // ========================================================================
    // Phase 4.1: Extension Preprocessing
    // ========================================================================
}

// Domain submodules — impl TransformEngine/JsTransformExecutor blocks live
// across these files; re-exports keep historical paths stable.
mod aggregation;
mod image;
mod js_executor;
mod operations;
mod pipeline;
mod value;

pub(crate) use image::*;
pub use js_executor::*;
pub(crate) use value::*;

#[cfg(test)]
mod tests;
